version: '3.8'

services:
  api-server:
    build: ./server
    container_name: api-server-test
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - app-db
      - user-db
    volumes:
      - ./server:/app
      - /app/node_modules

  app-db:
    image: mysql:8
    container_name: app-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - app_data:/var/lib/mysql
      - ./db/app/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-db:
    image: mysql:8
    container_name: user-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"
    volumes:
      - user_data:/var/lib/mysql
      - ./db/user/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  app_data:
  user_data:
