version: '3.8'

services:
  reverse-proxy:   # 외부에서 내부 네트워크로 접속하게 할 수 있는 기능
    image: nginx:stable
    container_name: reverse-proxy
    ports:
      - "443:443"  # 외부에서 443번 포트로 접근 가능
      - "80:80" # http 프로토콜로 접속했을 때 redirection 용도
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    depends_on:
      - api-server
    restart: always

  api-server:
    build: ./server
    container_name: api-server
    expose:
      - "3000"  # 내부에서만 3000번 포트로 접근 가능
    env_file:
      - .env
    depends_on:
      - user-db
      - app-db
    restart: always

  user-db:
    image: mysql:8
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    expose:
      - "3306"  # 내부에서만 3306번 포트로 접근 가능
    volumes:
      - user_data:/var/lib/mysql
      - ./db/user/init.sql:/docker-entrypoint-initdb.d/init.sql

  app-db:
    image: mysql:8
    container_name: app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    expose:
      - "3306"  # 내부에서만 3306번 포트로 접근 가능
    volumes:
      - app_data:/var/lib/mysql
      - ./db/app/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  user_data:
  app_data:
