version: '3.8'

services:
  api-server:
    build: ./server                     # server 폴더에 Dockerfile 있어야 함
    container_name: api-server-test
    env_file:
      - .env
    ports:
      - "3000:3000"

